# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'win1803'

steps:
- powershell: Invoke-WebRequest -Uri $url -OutFile $output
  displayName: 'Download Haskell Platform'
  env:
    url: "https://haskell.org/platform/download/8.6.2/HaskellPlatform-8.6.2-core-x86_64-setup.exe"
    output: "haskell-platform.exe"
- powershell: .\haskell-platform.exe /S
  displayName: 'Install Haskell Platform'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
